import AppHeader from "@/components/AppHeader";
import Footer from "@/components/Footer";
import { Box, Container } from "@mui/material";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Box sx={{ bgcolor: "white", minHeight: "100vh" }}>
          <Container>
            <AppHeader />
            {children}
          </Container>
          <Footer />
        </Box>
      </body>
    </html>
  );
}
